version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: grooming_system
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=dog_grooming
      - MYSQL_USER=root1
      - MYSQL_PASSWORD=db5113

    ports:
      - "3307:3306"